horbyshyn react-basics homework
kottans/chernivtsi-frontend-2019 pull request #13
Opened 2019-05-12 19:46 UTC by horbyshyn

2019-05-13 10:53 UTC, KinjinZzz commented
@horbyshyn there must be no submodules, please remove it and add homework directly to your folder.

2019-05-13 13:10 UTC, horbyshyn commented
> @horbyshyn there must be no submodules, please remove it and add homework directly to your folder.

fixed

2019-05-13 20:25 UTC, Kinjinka requested changes

2019-05-13 20:25 UTC, KinjinZzz commented on homeworks/react-basics/horbyshyn/src/App.js
> +      })
Don't forget to `catch()` errors

2019-05-13 20:25 UTC, KinjinZzz commented on homeworks/react-basics/horbyshyn/src/App.js
> +function RenderLecture(item, key){
It is bad practice to have few components in single file

2019-05-13 20:25 UTC, KinjinZzz commented on homeworks/react-basics/horbyshyn/src/App.js
> +    if(document.getElementById(id).classList.contains('hidden'))
Transform `Render Lecture` to class component and use state `hidden`, then you can handle state `onClick()` and render Lecture info only if `hidden` is `false`. You have to control logic in react using state, using dom will cause problem with rerender and will cause conflicts with few components with the same indexes.

2019-07-15 16:06 UTC, denysdovhan commented
Closed since requested changes aren't applied.

2019-07-15 16:06 UTC, closed without merging